name: suramerica
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.2.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  go_router: ^13.2.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: MontserratBold
      fonts:
        - asset: fonts/Montserrat-ExtraBold.ttf
    - family: BrandonGrotesque
      fonts:
        - asset: fonts/brandon-grotesque-light-58a8a4b38001d.otf