name: suramerica
description: A Flutter-based web app for Suramerica Tours, offering a platform to explore, book, and manage national and international tours. Features include tour browsing, multilingual support, and an intuitive booking interface.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.2.0
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  go_router: ^13.2.1
  google_fonts: ^6.2.1
  lints: ^2.1.1
  sliver_tools: ^0.2.12
  universal_html: ^2.2.4

dev_dependencies:
  lint: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.otf
        - asset: fonts/Montserrat-Bold.otf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.otf
          weight: 900
    - family: BrandonGrotesque
      fonts:
      - asset: fonts/Brandon_reg.otf
      - asset: fonts/Brandon_reg_it.otf
        style: italic
      - asset: fonts/Brandon_med.otf
        weight: 500
      - asset: fonts/Brandon_med_it.otf
        weight: 500
        style: italic
      - asset: fonts/Brandon_bld.otf
        weight: 700
      - asset: fonts/Brandon_bld_it.otf
        weight: 700
        style: italic
      - asset: fonts/Brandon_light.otf
        weight: 300
      - asset: fonts/Brandon_light_it.otf
        weight: 300
        style: italic
      - asset: fonts/Brandon_thin.otf
        weight: 100
      - asset: fonts/Brandon_thin_it.otf
        weight: 100
        style: italic
      - asset: fonts/Brandon_blk.otf
        weight: 900
      - asset: fonts/Brandon_blk_it.otf
        weight: 900
        style: italic
      